name: Activity Box

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: 4bigchoi23/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: thomasmerz
          GIST_ID: c8a8692eccc24f1476020f325a1647e2
